### PR TITLE
Created develop branch; added WalnutGulch and Stehekin at 1/16 resolution

### PR DESCRIPTION
**Pull request by tbohn**
This PR:
 - Creates a `develop` branch
 - Adds a `WalnutGulch` subdirectory under `image`
 - Adds 1/16 degree resolution parameters for `Stehekin`

Description:
 - `WalnutGulch` contains the Walnut Gulch Experimental Watershed in southern Arizona, maintained by the USDA.  This basin has numerous rain gauges and several flumes.  There are also 2 Ameriflux eddy covariance towers in this watershed.

 - Note: VIC should not be expected to reproduce channel flows well in this basin, due primarily to channel losses (groundwater recharge).  However, the rain gauges and flux towers ought to provide good observations for evaluating VIC's P-ET behavior over more than a single point.

 - The domain at this point is simply a box at 1/16 degree resolution, containing the basin - I haven't done a more sophisticated delineation. (`domain.WalnutGulch.0.0625_deg.nc`)

 - Forcings are from Livneh et al (2015) at 1/16 degree resolution, for the year 2008.

 - There are 2 sets of parameters (again, at 1/16 degree resolution):
 -- `params.WalnutGulch.L2015.nc`: parameters taken from the Livneh et al (2015) dataset, and converted to image mode/netcdf by the `tonic` tool.
 -- `params.WalnutGulch.MOD_IGBP.nc`: same as `L2015`, but with vegetation classes, tile fractions, and properties `LAI`, `Fcanopy`, and `Albedo` derived from MODIS products (to be described in a paper in preparation by Bohn et al.). 

 - There are 3 global parameter files, with names indicating which of the 2 parameter files they correspond to:
 -- `global_param.WalnutGulch.L2015.nc`
 -- `global_param.WalnutGulch.MOD_IGBP.nc`: here, the `FCAN_SRC` is set to `FROM_DEFAULT` for consistency with the L2015 parameters
 -- `global_param.WalnutGulch.MOD_IGBP.Fcanopy.nc`: here, the `FCAN_SRC` is set to `FROM_VEGPARAM` to evaluate the Fcanopy values

A set of analogous files has been added to `Stehekin`.  The 1/16 degree forcings for `Stehekin` are simply sub-sampled (via nearest neighbor) from the previous 1/8 degree forcings.

### CODE REVIEW

**Comment by jhamman** [comment]
@dgergel or @yixinmao - can one (or both) of you give these files a test by running them against the current image driver on the develop branch? These provide a test case with updated parameters, including inputs for the fcan parameter option.

**Comment by tbohn** [comment]
At some point it might be good to replace Stehekin with some other basin from the Pacific Northwest that has better observations.  Stehekin was a rather arbitrary choice that was made (by me) in a hurry just to set up a sample dataset.

**Comment by dgergel** [comment]
@jhamman and @tbohn: I have run these files and the runs completed successfully. The one thing I needed to change in the global parameter files is that the subdirectory under `VIC_sample_data/image/WalnutGulch/` should be `parameters` and not `params` as it currently is in the global parameter files to agree with the current directory structure of `VIC_sample_data`. I can share the output files if that would be useful.

**Comment by tbohn** [comment]
Thanks @dgergel - I've replaced `params` with `parameters` in the global parameter files.

**Pull request merged**
